server:
  port: 9001

spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.0.107:8848
      config:
        server-addr: http://192.168.0.107:8848
        file-extension: yaml

